GET http://localhost:3000/products

###
GET http://localhost:3000/products/685518f9-565c-46a7-9a39-fc68320ce79a

###
POST http://localhost:3000/products
Content-Type: application/json

{
   "name":"pc boladasso",
   "description":"Mussum Ipsum, cacilds",
   "image_url":"https://images.unsplash.com/photo-1545155277-5d5075713c86?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80",
   "price":5000.00
}

###
PATCH http://localhost:3000/products/685518f9-565c-46a7-9a39-fc68320ce79a
Content-Type: application/json

{
   "name":"tv 321",
   "price":1500.91
}

###
DELETE http://localhost:3000/products/3256a19a-9135-46bd-b841-723a323e30b8