GET http://localhost:3002/credit-cards

###
POST http://localhost:3002/credit-cards
Content-Type: application/json

{
   "name":"Felippe",
   "number":"1111111111111105"
}

###
GET http://localhost:3002/invoices